services:
  reth:
    build:
      context: .
      dockerfile: reth/Dockerfile
    ports:
      - "8545:8545"       # RPC
      - "8546:8546"       # websocket
      - "7301:6060"       # metrics
      - "30303:30303"     # P2P TCP
      - "30303:30303/udp" # P2P UDP
      - "8551:8551"       # auth rpc
    command: [ "bash", "./execution-entrypoint" ]
    volumes:
        - ./reth-data:/data
        - ./config:/chainconfig
    env_file:
     - .env.mainnet
  node:
    build:
      context: .
      dockerfile: reth/Dockerfile
    ports:
      - "7545:8545"     # RPC
      - "9222:9222"     # P2P TCP
      - "9222:9222/udp" # P2P UDP
      - "7300:7300"     # metrics
      - "6060:6060"     # pprof
    command: [ "bash", "./op-node-entrypoint" ]
    env_file:
     - .env.mainnet
  prometheus:
    image: prom/prometheus:latest
    env_file:
      - .env.mainnet
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana:9.3.0
    env_file:
      -  .env.mainnet
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  prometheus_data:
  grafana_data: